[package]
name = "passqr"
version = "0.1.0"
edition = "2024"
rust-version = "1.92"

[dependencies]
serde = { version = "1", features = ["derive"] }
toml = { version = "0.9", features = ["preserve_order"] }
qrcode = "0.14"
image = "0.25"
printpdf = "0.8"
